config/routes.rb
Rails.application.routes.draw do

  resources :registrations do
    resources :events
  end

  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end

  devise_for :users
  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registration
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :registrations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
# #3
  skip_before_action :verify_authenticity_token

  before_filter :set_access_control_headers

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    @registration = Registration.find_by(url: request.env['HTTP_ORIGIN'])

    unless @registration
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = @registration.events.new(event_params)

      if @event.save
        render json: @event, status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    end    
  end

  def preflight
    head 200
  end

  private
  def event_params
    params.require(:event).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :set_registration

  # GET /events
  def index
    @events = Event.all
  end

  # GET /events/1
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  def create
    @event = @registration.events.new(event_params)

    if @event.save
      redirect_to @registration, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /events/1
  def update
    if @event.update(event_params)
      redirect_to @event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /events/1
  def destroy
    @event.destroy
    redirect_to events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params.require(:event).permit(:name)
    end

    def set_registration
      @registration = Registration.find(params[:registration_id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @registrations = current_user.registrations
  end

  def show
    @registration = Registration.find(params[:id])
    @events = @registration.events.group_by(&:name)
  end

  def new
    @registration = Registration.new
  end

  def edit
    @registration = Registration.find(params[:id])
  end

  def create
    @registration = current_user.registrations.new(registration_params)

    if @registration.save
      flash[:notice] = "Website has been registered."
      redirect_to registrations_path
    else
      flash.now[:alert] = "There was an error registering the website."
      render :new
    end
  end

  def destroy
    @registration = Registration.find(params[:id])

    if @registration.destroy
      flash[:notice] = "\"#{@registration.name}\" was deleted successfully."
      redirect_to registrations_path
    else
      flash.now[:alert] = "There was an error deleting the post."
      render :index
    end
  end

  private

  def registration_params
    params.require(:registration).permit([:name, :url])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= form_for [@registration, @event] do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form' %>

<%= link_to 'Back', :back %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Registration:</strong>
  <%= @event.registration %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NewRailsProject</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag "https://www.google.com/jsapi", "chartkick" %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
  <% if user_signed_in? %>
    Signed in as: <strong><%= current_user.email %></strong> |
    <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %> - <%= link_to "View My Sites", registrations_path, method: :get, :class => 'navbar-link' %>
  <% else %>
    <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
    <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
  <% end %>

  <div class="flash">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash.now[:alert] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash.now[:alert] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  </div>

<%= yield %>

</div>
</body>
</html>

app/views/registered_applications/index.html.erb
<h1>List of Registered Websites</h1>
<% @registrations.each do |registration| %>
  <%= registration.name %>
<% end %>

app/views/registered_applications/new.html.erb
<h1>Register a New Site</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @registration, as: :registration, url: registered_applications_path, method: :post do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="form-group">
      <%= f.submit "Save" %>
    </div>
    <% end %>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="jumbotron">
    <h2>Ted's Analytics App</h2>
    <p>Welcome to the Future</p>
</div>